<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class YxGroup extends Model
{



    /**
     *  获取所有组员
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function members() {
        return $this->hasMany('App\User');
    }

    /**
     * 追加字段
     * @var array
     */
    protected $appends = [
        'members'
    ];

    /**
     * 获取队员
     */
    public function getMembersAttribute() {
        return $this->members()->get();
    }



    static public function getTeamCount() {
        return YxGroup::count();
    }


    /**
     * 删除队伍
     * @return bool|null
     * @throws \Exception
     */
    public function delete()
    {
        $members = $this->members()->get();
        foreach ($members as $member) {
            $member->yx_group_id = null;
            $memberState = $member->state()->first();
            $memberState->state = 1;
            $member->save();
            $memberState->save();
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }


    /**
     * 通知队长
     */
    public function notifyCaptain() {

    }


}
